"""PRD-023: Comment warmup scheduling + execution.

Schedules and posts warmup comments on prospect content
before transitioning them to ready_for_dm.
"""

import logging
from datetime import datetime, timedelta, timezone

import httpx

from .config import SAFARI_PORTS
from .daily_caps import check_cap, increment_cap
from .db.queries import (
    create_warmup_schedule,
    get_contacts_by_stage,
    get_pending_warmups,
    mark_warmup_sent,
    mark_warmup_failed,
    update_contact_stage,
    log_funnel_event,
)
from .state_machine import validate_transition

logger = logging.getLogger(__name__)


async def schedule_warmups(
    client: httpx.AsyncClient,
    *,
    comments_required: int = 3,
    interval_hours: int = 24,
    dry_run: bool = False,
) -> dict:
    """Create warmup comment schedules for qualified contacts."""
    contacts = await get_contacts_by_stage(client, "qualified", limit=20)
    scheduled = 0

    for contact in contacts:
        contact_id = contact["id"]
        platform = contact.get("platform", "")
        if platform not in SAFARI_PORTS or "comments" not in SAFARI_PORTS.get(platform, {}):
            continue

        now = datetime.now(timezone.utc)
        for i in range(comments_required):
            scheduled_at = now + timedelta(hours=interval_hours * (i + 1))
            if not dry_run:
                await create_warmup_schedule(
                    client,
                    contact_id=contact_id,
                    platform=platform,
                    post_url="",  # Will be filled by content scanner
                    comment_text="",  # Will be generated by Claude
                    scheduled_at=scheduled_at.isoformat(),
                )

        if not dry_run:
            validate_transition("qualified", "warming")
            await update_contact_stage(client, contact_id, "warming")
            await log_funnel_event(
                client,
                contact_id=contact_id,
                from_stage="qualified",
                to_stage="warming",
                triggered_by="warmup_agent",
                metadata={"comments_scheduled": comments_required},
            )
        scheduled += 1

    return {"contacts_scheduled": scheduled, "total_qualified": len(contacts)}


async def execute_warmups(
    client: httpx.AsyncClient,
    *,
    dry_run: bool = False,
) -> dict:
    """Execute due warmup comments via Safari comment services."""
    warmups = await get_pending_warmups(client, limit=10)
    sent = 0
    failed = 0

    for warmup in warmups:
        platform = warmup["platform"]
        allowed, current, limit = await check_cap(client, platform, "comment")
        if not allowed:
            logger.info(f"[warmup] Daily cap reached for {platform} comments ({current}/{limit})")
            continue

        if dry_run:
            logger.info(f"[dry-run] Would send warmup comment: {warmup['id']}")
            sent += 1
            continue

        try:
            port = SAFARI_PORTS.get(platform, {}).get("comments")
            if not port:
                await mark_warmup_failed(client, warmup["id"], "No comment service for platform")
                failed += 1
                continue

            resp = await client.post(
                f"http://localhost:{port}/api/comment",
                json={
                    "postUrl": warmup["post_url"],
                    "comment": warmup["comment_text"],
                },
                timeout=30.0,
            )
            resp.raise_for_status()
            await mark_warmup_sent(client, warmup["id"])
            await increment_cap(client, platform, "comment")
            sent += 1

        except Exception as e:
            logger.error(f"[warmup] Failed to send comment: {e}")
            await mark_warmup_failed(client, warmup["id"], str(e))
            failed += 1

    return {"sent": sent, "failed": failed, "total_due": len(warmups)}
