#!/usr/bin/env python3
"""Extra features to push each ACTP Lite system to 250+."""

def _extra_nextjs(P, name):
    """Additional features common to all Next.js services (~70 features)."""
    return [
        # Database (15)
        (f"{P}-DB-001", "Supabase connection pooling for serverless functions"),
        (f"{P}-DB-002", "Database query timeout handling (5s default)"),
        (f"{P}-DB-003", "Optimistic locking for concurrent updates"),
        (f"{P}-DB-004", "Soft delete pattern for important records"),
        (f"{P}-DB-005", "Database index optimization for all query patterns"),
        (f"{P}-DB-006", "Query result caching with TTL for frequent reads"),
        (f"{P}-DB-007", "Batch insert/update for bulk operations"),
        (f"{P}-DB-008", "Database error classification (transient vs permanent)"),
        (f"{P}-DB-009", "Connection retry logic with exponential backoff"),
        (f"{P}-DB-010", "Row-level security policies for all tables"),
        (f"{P}-DB-011", "Database migration tracking in actp_migrations table"),
        (f"{P}-DB-012", "Query performance logging for slow queries (>1s)"),
        (f"{P}-DB-013", "Pagination using cursor-based approach for large datasets"),
        (f"{P}-DB-014", "JSON schema validation for JSONB columns"),
        (f"{P}-DB-015", "Database vacuum/analyze recommendations in health check"),
        # Monitoring (10)
        (f"{P}-MON-001", "Structured JSON logging for all operations"),
        (f"{P}-MON-002", "Request/response timing metrics logged"),
        (f"{P}-MON-003", "Error rate tracking per endpoint"),
        (f"{P}-MON-004", "API usage analytics (calls per endpoint per day)"),
        (f"{P}-MON-005", "Supabase connection health monitoring"),
        (f"{P}-MON-006", "Memory usage monitoring in serverless context"),
        (f"{P}-MON-007", "Cold start detection and logging"),
        (f"{P}-MON-008", "Request ID generation for tracing across services"),
        (f"{P}-MON-009", "Error alerting integration (log critical errors)"),
        (f"{P}-MON-010", "Performance baseline tracking for regression detection"),
        # Deployment (10)
        (f"{P}-DEP-001", "Vercel deployment configuration validated"),
        (f"{P}-DEP-002", "Environment variables set in Vercel project settings"),
        (f"{P}-DEP-003", "Production build succeeds with zero errors"),
        (f"{P}-DEP-004", "Vercel function size within limits (<50MB)"),
        (f"{P}-DEP-005", "Preview deployments for PRs enabled"),
        (f"{P}-DEP-006", "Custom domain configuration (if applicable)"),
        (f"{P}-DEP-007", "Git integration for automatic deployments"),
        (f"{P}-DEP-008", "Rollback capability via Vercel dashboard"),
        (f"{P}-DEP-009", "Health check passes after deployment"),
        (f"{P}-DEP-010", "Deployment documentation in README"),
        # Integration (15)
        (f"{P}-INT-001", "Cross-service API key management via shared Supabase"),
        (f"{P}-INT-002", "Consistent error response format across all Lite services"),
        (f"{P}-INT-003", "Service discovery via environment variables"),
        (f"{P}-INT-004", "Webhook notification to HookLite on key events"),
        (f"{P}-INT-005", "Activity log entries include service name for multi-service tracing"),
        (f"{P}-INT-006", "Shared Supabase types generated from database schema"),
        (f"{P}-INT-007", "API versioning strategy (v1 prefix or header)"),
        (f"{P}-INT-008", "Cross-service health aggregation support"),
        (f"{P}-INT-009", "Shared date/time handling (UTC everywhere, display local)"),
        (f"{P}-INT-010", "Consistent pagination format: {data, total, limit, offset}"),
        (f"{P}-INT-011", "Service-to-service authentication with dedicated API keys"),
        (f"{P}-INT-012", "Retry logic for cross-service API calls"),
        (f"{P}-INT-013", "Circuit breaker pattern for external API calls"),
        (f"{P}-INT-014", "Request correlation IDs passed between services"),
        (f"{P}-INT-015", "Graceful degradation when dependent services are down"),
        # Documentation (10)
        (f"{P}-DOC-001", "API endpoint documentation in README with curl examples"),
        (f"{P}-DOC-002", "Environment variable documentation with descriptions"),
        (f"{P}-DOC-003", "Architecture diagram in README"),
        (f"{P}-DOC-004", "Database schema documentation"),
        (f"{P}-DOC-005", "CLI usage documentation with examples"),
        (f"{P}-DOC-006", "Deployment guide (Vercel setup steps)"),
        (f"{P}-DOC-007", "Troubleshooting guide for common issues"),
        (f"{P}-DOC-008", "Integration guide: how this service connects to others"),
        (f"{P}-DOC-009", "CHANGELOG tracking for version history"),
        (f"{P}-DOC-010", "Contributing guide with code style rules"),
        # Performance (10)
        (f"{P}-PERF-001", "API response time < 500ms for all endpoints"),
        (f"{P}-PERF-002", "Database queries use indexes (no sequential scans)"),
        (f"{P}-PERF-003", "JSON payload size limits enforced"),
        (f"{P}-PERF-004", "Gzip compression on API responses"),
        (f"{P}-PERF-005", "Efficient pagination (no COUNT(*) on large tables)"),
        (f"{P}-PERF-006", "Minimal Supabase client initialization (reuse connections)"),
        (f"{P}-PERF-007", "Static page generation for dashboard where possible"),
        (f"{P}-PERF-008", "Image/asset optimization for dashboard UI"),
        (f"{P}-PERF-009", "Bundle size optimization (tree-shaking, code splitting)"),
        (f"{P}-PERF-010", "Lazy loading for dashboard components below fold"),
    ]

def _extra_worker(P):
    """Additional features for actp-worker (~100 features)."""
    return [
        # Auth & Security (10)
        (f"{P}-SEC-001", "API keys stored securely in .env (never in code)"),
        (f"{P}-SEC-002", "HTTPS-only for all API calls to cloud services"),
        (f"{P}-SEC-003", "Temp file permissions set restrictively"),
        (f"{P}-SEC-004", "No sensitive data in log output"),
        (f"{P}-SEC-005", "Validate all API responses before processing"),
        (f"{P}-SEC-006", "Sanitize file paths to prevent traversal attacks"),
        (f"{P}-SEC-007", "Rate limit outbound API calls to respect service limits"),
        (f"{P}-SEC-008", "Secure random worker ID generation"),
        (f"{P}-SEC-009", "Validate video file integrity after download"),
        (f"{P}-SEC-010", "Credential rotation support without restart"),
        # Monitoring (10)
        (f"{P}-MON-001", "Structured JSON logging for all operations"),
        (f"{P}-MON-002", "Job execution timing metrics"),
        (f"{P}-MON-003", "Error rate tracking per executor"),
        (f"{P}-MON-004", "System resource monitoring (CPU, memory, disk)"),
        (f"{P}-MON-005", "Network connectivity health checks"),
        (f"{P}-MON-006", "Log rotation for long-running daemon"),
        (f"{P}-MON-007", "Performance baseline tracking"),
        (f"{P}-MON-008", "Alert on consecutive failures (>3)"),
        (f"{P}-MON-009", "Daily summary log with jobs processed/failed"),
        (f"{P}-MON-010", "Uptime tracking since last restart"),
        # Integration (15)
        (f"{P}-INT-001", "MPLite API client with full error handling"),
        (f"{P}-INT-002", "GenLite API client with full error handling"),
        (f"{P}-INT-003", "Supabase Storage upload client"),
        (f"{P}-INT-004", "Supabase heartbeat writer with retry"),
        (f"{P}-INT-005", "Supabase log writer with batch support"),
        (f"{P}-INT-006", "Cross-service request correlation IDs"),
        (f"{P}-INT-007", "Service health check before polling"),
        (f"{P}-INT-008", "Graceful handling when cloud services are down"),
        (f"{P}-INT-009", "Queue priority ordering respected in polling"),
        (f"{P}-INT-010", "Worker reports service versions in heartbeat"),
        (f"{P}-INT-011", "Support for future AdLite local tasks"),
        (f"{P}-INT-012", "Plugin architecture for adding new pollers"),
        (f"{P}-INT-013", "Plugin architecture for adding new executors"),
        (f"{P}-INT-014", "Configuration hot-reload without restart"),
        (f"{P}-INT-015", "Multi-worker coordination (prevent double-claim)"),
        # Database (10)
        (f"{P}-DB-001", "Supabase client with connection pooling"),
        (f"{P}-DB-002", "Heartbeat upsert with conflict resolution"),
        (f"{P}-DB-003", "Log batch insertion for efficiency"),
        (f"{P}-DB-004", "Worker registration on first heartbeat"),
        (f"{P}-DB-005", "Historical heartbeat data retention (30 days)"),
        (f"{P}-DB-006", "Worker log pruning (keep 7 days)"),
        (f"{P}-DB-007", "Job completion stats tracked in Supabase"),
        (f"{P}-DB-008", "Error history stored per job type"),
        (f"{P}-DB-009", "Daily aggregated stats written to Supabase"),
        (f"{P}-DB-010", "Database error handling with retry"),
        # Documentation (10)
        (f"{P}-DOC-001", "README with installation, setup, usage"),
        (f"{P}-DOC-002", "Environment variable documentation"),
        (f"{P}-DOC-003", "Architecture diagram with data flow"),
        (f"{P}-DOC-004", "Executor documentation with supported platforms"),
        (f"{P}-DOC-005", "CLI reference with all commands"),
        (f"{P}-DOC-006", "Troubleshooting guide"),
        (f"{P}-DOC-007", "launchd setup guide for auto-start"),
        (f"{P}-DOC-008", "Integration guide: connecting to cloud services"),
        (f"{P}-DOC-009", "Contributing guide"),
        (f"{P}-DOC-010", "CHANGELOG"),
        # Performance (10)
        (f"{P}-PERF-001", "Async I/O for all network operations"),
        (f"{P}-PERF-002", "Video download streaming (no full buffer in memory)"),
        (f"{P}-PERF-003", "Concurrent uploads to Supabase Storage"),
        (f"{P}-PERF-004", "Efficient poll interval (adaptive based on queue depth)"),
        (f"{P}-PERF-005", "Memory-efficient video handling (stream processing)"),
        (f"{P}-PERF-006", "Minimal CPU usage when idle"),
        (f"{P}-PERF-007", "Batch heartbeat updates when multiple jobs active"),
        (f"{P}-PERF-008", "Connection reuse for HTTP clients"),
        (f"{P}-PERF-009", "Temp directory cleanup on startup"),
        (f"{P}-PERF-010", "Resource usage stays under 500MB RAM"),
        # Deployment (10)
        (f"{P}-DEP-001", "pip install -e . for development"),
        (f"{P}-DEP-002", "Virtual environment setup script"),
        (f"{P}-DEP-003", "launchd plist auto-generation"),
        (f"{P}-DEP-004", "Homebrew formula (future)"),
        (f"{P}-DEP-005", "Version check on startup"),
        (f"{P}-DEP-006", "Auto-update check (future)"),
        (f"{P}-DEP-007", "Dependency pinning in requirements.txt"),
        (f"{P}-DEP-008", "Python version check on startup (3.11+)"),
        (f"{P}-DEP-009", "First-run setup wizard"),
        (f"{P}-DEP-010", "Uninstall script for clean removal"),
        # Extra tests (15)
        (f"{P}-XTEST-001", "Test video download streaming"),
        (f"{P}-XTEST-002", "Test Supabase Storage upload with real credentials"),
        (f"{P}-XTEST-003", "Test heartbeat survives Supabase outage"),
        (f"{P}-XTEST-004", "Test multiple workers don't double-claim"),
        (f"{P}-XTEST-005", "Test log rotation doesn't lose entries"),
        (f"{P}-XTEST-006", "Test adaptive poll interval adjusts correctly"),
        (f"{P}-XTEST-007", "Test memory usage stays under limit"),
        (f"{P}-XTEST-008", "Test disk space check prevents download when full"),
        (f"{P}-XTEST-009", "Test launchd plist generates correctly"),
        (f"{P}-XTEST-010", "Test graceful degradation with partial capabilities"),
        (f"{P}-XTEST-011", "Load test: 10 concurrent jobs"),
        (f"{P}-XTEST-012", "Test config hot-reload"),
        (f"{P}-XTEST-013", "Test worker ID uniqueness"),
        (f"{P}-XTEST-014", "Test all CLI subcommands return 0"),
        (f"{P}-XTEST-015", "Benchmark: job completion time by executor type"),
    ]

EXTRA = {
    "metricslite": ("ML", _extra_nextjs),
    "genlite": ("GL", _extra_nextjs),
    "adlite": ("AL", _extra_nextjs),
    "actpdash": ("AD", _extra_nextjs),
    "hooklite": ("HL", _extra_nextjs),
    "mediaposter-lite": ("MP", _extra_nextjs),
    "actp-worker": ("WK", _extra_worker),
}

def get_extras(service_id):
    prefix, fn = EXTRA[service_id]
    if fn == _extra_worker:
        return fn(prefix)
    return fn(prefix, service_id)
