"""Expand ACTP features from 75 to ~300 with fine-grained coverage."""
import json

FL = "/Users/isaiahdupree/Documents/Software/MediaPoster/Backend/services/creative_testing_pipeline/feature_list.json"

# Each tuple: (category, name, description, criteria_list)
NEW = []
def a(cat, name, desc, crit):
    NEW.append((cat, name, desc, crit))

# DATABASE (18)
a("database","Composite indexes on performance_logs","Composite index (creative_id,metric_type,measured_at) for time-series queries",["Index created","EXPLAIN verified"])
a("database","Materialized view for campaign summaries","Aggregate round/creative/spend/score per campaign",["View created","Refresh trigger"])
a("database","Materialized view for creative leaderboard","Rank creatives by score across campaigns",["View created","Refresh on update"])
a("database","Database seed script for development","Idempotent seed creating sample campaigns/creatives",["Idempotent","Sample data"])
a("database","Soft delete on campaigns","deleted_at column, filtered in queries",["Column added","Query filter"])
a("database","Data retention policy for performance_logs","Auto-delete logs older than 90 days",["Retention config","Cleanup job"])
a("database","Full-text search on creatives","tsvector on hook/cta/angle/script with GIN index",["tsvector trigger","GIN index","Search function"])
a("database","Audit log table for state changes","Track status changes with actor/timestamp",["Table created","Trigger on update"])
a("database","TypeScript type generation from schema","Auto-generate TS types from Supabase",["Gen script","Output file"])
a("database","Connection pooling configuration","Pool size/timeout for concurrent ops",["Pool config","Health check"])
a("database","Migration version tracking","Version table for safe upgrades",["Version table","Runner script"])
a("database","Indexes on organic_posts platform/status","Fast filtering by platform and status",["Indexes added","EXPLAIN verified"])
a("database","Indexes on ad_deployments status/platform","Fast filtering by status and platform",["Indexes added","EXPLAIN verified"])
a("database","Unique constraint organic_posts creative+platform","Prevent duplicate posts",["Constraint added","Upsert handling"])
a("database","JSONB validation on config columns","Check constraints for required keys",["Constraint added","Error on invalid"])
a("database","Cascade delete verification","ON DELETE CASCADE from campaign through all children",["Cascade tested","No orphans"])
a("database","Database backup before migration","Backup ACTP tables before schema changes",["Backup script","Restore tested"])
a("database","Row count monitoring for ACTP tables","Track counts for capacity planning",["Count query","Dashboard metric"])

# ORCHESTRATOR (15)
a("orchestrator","Campaign cloning","Clone campaign with config/angles/audience",["Clone endpoint","New IDs","Config copied"])
a("orchestrator","Campaign archival","Archive completed campaigns",["Archive status","Filter from active"])
a("orchestrator","Round retry on failure","Retry failed round from last good state",["Retry endpoint","State rollback","Max retries"])
a("orchestrator","Round timeout handling","Auto-fail stuck rounds after timeout",["Timeout config","Auto-transition","Alert"])
a("orchestrator","Campaign progress percentage","Progress bar: completed/total rounds",["Calculation","API field"])
a("orchestrator","Campaign summary stats auto-update","Auto-update totals on mutations",["Trigger/hook","Consistent counts"])
a("orchestrator","Concurrent campaign limit","Max active campaigns config",["Enforced on create","Error message"])
a("orchestrator","Campaign tags and labels","Tags for organizing by product/niche",["Tags column","Filter by tag","CRUD"])
a("orchestrator","Campaign history log","All state transitions with timestamps",["History table","Logged on transition"])
a("orchestrator","Webhook on state change","Fire webhook on campaign/round transitions",["URL config","POST payload","Retry"])
a("orchestrator","Campaign templates","Save/reuse campaign configs as templates",["Template CRUD","Create from template"])
a("orchestrator","Bulk campaign operations","Pause/resume/archive multiple at once",["Bulk endpoints","Transaction safety"])
a("orchestrator","Campaign duration tracking","Track elapsed time start→completion",["Duration calc","In summary"])
a("orchestrator","Round auto-creation on completion","Auto-create next round per strategy",["Strategy config","Cycle logic"])
a("orchestrator","Pipeline dry-run mode","Full pipeline without publish/spend",["Dry-run flag","Skip publish/deploy"])

# CREATIVE ENGINE (25)
a("creative","Thumbnail auto-generation from video","Extract best frame via FFmpeg",["Frame extraction","Quality check"])
a("creative","Video transcoding per platform specs","Platform-specific codecs/bitrates",["Spec map","FFmpeg transcode"])
a("creative","Caption/subtitle overlay on video","Whisper transcription + FFmpeg drawtext",["Whisper","SRT","Burn-in"])
a("creative","Voiceover generation with TTS","ElevenLabs/OpenAI TTS from script",["TTS call","Audio storage","Duration match"])
a("creative","Background music selection and mixing","Royalty-free music + FFmpeg mix",["Music library","Volume ducking"])
a("creative","Video duration variants (5s/15s/30s/60s)","Multiple duration cuts per brief",["Duration param","Pacing adjustment"])
a("creative","Creative preview endpoint","Preview video/thumbnail/metadata via API",["Signed URL","Metadata included"])
a("creative","Video quality validation","Validate resolution/duration/codec/size",["Resolution","Duration","Codec","File size"])
a("creative","Creative tagging system","Tags for emotion/style/visual elements",["Tags field","Auto-tag","Filter"])
a("creative","Creative search and filter","Search by hook/angle/score/source/tags",["FTS","Score filter","Source filter"])
a("creative","Batch generation with progress","Batch jobs with real-time progress",["Job ID","Progress %","Partial completion"])
a("creative","Generation cost estimation","Estimate API costs before generating",["Cost per provider","Budget check"])
a("creative","Generation queue with priority","Priority queue for generation jobs",["Queue","Priority","Concurrency limit"])
a("creative","Hook text overlay on video","Animated hook text in first 3 seconds",["Text position","Animation","Safe zone"])
a("creative","CTA overlay animation on video","CTA text/button in last 3 seconds",["CTA position","Animation","Link indicator"])
a("creative","Creative duplicate detection","Detect near-duplicates before generating",["Similarity score","Threshold","Skip/warn"])
a("creative","Video compression for upload","Compress to meet platform size limits",["Target size","CRF optimization"])
a("creative","Safe zone template overlay","Platform safe zones to prevent text cutoff",["TikTok zone","YT zone","IG zone"])
a("creative","Creative expiry and cleanup","Auto-delete non-winner files after period",["Expiry config","Skip winners"])
a("creative","Frame extraction for thumbnail candidates","5-10 frames scored for quality",["FFmpeg","Quality scoring","Best pick"])
a("creative","Script readability scoring","Score scripts for clarity/effectiveness",["Reading level","CTA strength"])
a("creative","Multi-language creative generation","Generate in multiple languages",["Language param","Translation","Per-lang TTS"])
a("creative","Creative approval workflow","Optional human approval before publish",["Approval queue","Approve/reject"])
a("creative","Image ad generation for static placements","DALL-E static ads from brief",["DALL-E","Platform dims","Text overlay"])
a("creative","Audio-only ad for podcast testing","TTS audio ads from script",["TTS","Audio format","Duration control"])

# PUBLISHING (20)
a("publishing","Hashtag optimization per platform","AI-generated trending hashtags",["Platform-specific","Trending API","Max count"])
a("publishing","Optimal posting time calculator","Best times from historical data",["Historical analysis","Platform-specific","Timezone"])
a("publishing","Caption A/B variants","Same video different captions",["Variant tracking","Map to post","Compare results"])
a("publishing","Cross-posting deduplication","Prevent duplicate posts to same platform",["Check before publish","Unique constraint"])
a("publishing","Post preview/draft mode","Preview before publishing",["Preview endpoint","Platform rendering"])
a("publishing","Publish retry with exponential backoff","Retry failed publishes",["Max retries","Backoff","Dead letter"])
a("publishing","Platform credential validation","Validate tokens before publish",["Token check","Auto-refresh","Clear error"])
a("publishing","Platform rate limit tracking","Track and respect API limits",["Rate limit headers","429 handling","Quota tracking"])
a("publishing","Post deletion/unlisting","Delete or unlist underperformers",["Delete API","Unlist","Update status"])
a("publishing","Post caption update","Edit caption of published post",["Edit API","Track original vs edited"])
a("publishing","Scheduled publish queue management","View/reorder/cancel queued publishes",["Queue list","Cancel","Reorder"])
a("publishing","Platform health check before publish","Check API availability first",["Health ping","Circuit breaker"])
a("publishing","Post URL verification after publish","Verify post is live (200 check)",["HEAD request","Retry if 404"])
a("publishing","Platform-specific caption formatting","Line breaks/emoji/mentions per platform",["Formatter","Platform rules"])
a("publishing","Character limit validation","Validate caption length per platform",["YT 5000","TT 2200","IG 2200"])
a("publishing","Video spec validation per platform","Duration/resolution/size/codec checks",["Spec map","Auto-transcode"])
a("publishing","First comment automation","Post first comment with offer link",["Comment API","Text config"])
a("publishing","Publish to Twitter/X","Post via Blotato integration",["Blotato API","Video upload","Track ID"])
a("publishing","Publish to Facebook page","Post via Meta Graph API",["Graph API","Page selection","Track ID"])
a("publishing","Cross-platform publish orchestration","Staggered timing with error isolation",["Stagger config","Independent errors"])

# ANALYTICS (25)
a("analytics","Hourly metric snapshots","Collect at 1h/3h/6h/12h/24h/48h",["Intervals","Snapshot table","Delta calc"])
a("analytics","Engagement decay curve calculation","Engagement rate over time, half-life",["Time-series","Decay rate","Chart data"])
a("analytics","Viral coefficient calculation","Share-to-view ratio, secondary reach",["Share/view ratio","Viral threshold"])
a("analytics","Comment keyword extraction","TF-IDF keywords from comments",["Fetch comments","Frequency analysis"])
a("analytics","Competitor benchmark data","Track competitor ad performance",["Benchmark storage","Relative scoring"])
a("analytics","Metric spike/drop alerting","Alert on significant metric changes",["Threshold config","Spike detection","Notification"])
a("analytics","View velocity curve data","Views per hour time-series",["Hourly counts","Peak detection"])
a("analytics","Likes-to-views ratio tracking","Track and trend L/V ratio",["Ratio calc","Trend direction"])
a("analytics","Share-to-view ratio tracking","Track S/V ratio for virality",["Ratio calc","Platform comparison"])
a("analytics","Completion rate by video second","Drop-off analysis for hook optimization",["Retention per second","Drop-off point"])
a("analytics","Audience retention curve","Viewer retention through video",["Retention %","Avg watch time","Chart data"])
a("analytics","Geographic performance breakdown","Metrics by country/region",["Geo data","Per-country breakdown"])
a("analytics","Device type breakdown","Mobile vs desktop vs tablet",["Device data","Per-device performance"])
a("analytics","Traffic source breakdown","Views by source: search/browse/external",["Source data","Platform-specific"])
a("analytics","Peak engagement time detection","Best time of day for engagement",["Hourly data","Peak detection"])
a("analytics","Creative-to-creative comparison","Side-by-side metric comparison",["Comparison endpoint","Delta calc"])
a("analytics","Metric data export CSV/JSON","Export metrics for campaign/round/creative",["CSV","JSON","Filters"])
a("analytics","Metric data validation and dedup","Validate and deduplicate collections",["Idempotent","Range validation"])
a("analytics","Metric backfill for missed intervals","Detect and fill collection gaps",["Gap detection","Backfill trigger"])
a("analytics","Aggregate metrics per round","Avg score/total views/spend per round",["Aggregate function","Stored on complete"])
a("analytics","Aggregate metrics per campaign","Campaign-level aggregates for dashboard",["Campaign aggregate","Trend direction"])
a("analytics","Metric anomaly detection","Detect bot traffic or API errors",["Statistical anomaly","Zero drops"])
a("analytics","Attribution pixel/UTM setup","Generate tracking pixels/UTMs per creative",["UTM generation","Pixel config"])
a("analytics","ROAS calculation per creative","Return on ad spend per creative",["Revenue input","Spend data","ROAS metric"])
a("analytics","Real-time metric streaming SSE","Server-sent events for live updates",["SSE endpoint","Push on new data"])

# WINNER SELECTION (12)
a("selection","Multi-armed bandit exploration","Thompson Sampling for dynamic selection",["Beta distribution","Exploration param"])
a("selection","Bayesian confidence scoring","Posterior probability per creative",["Prior","Update","Confidence interval"])
a("selection","Tie-breaking rules","Deterministic: newer > higher views > random",["Tie detection","Ordered fallbacks"])
a("selection","Winner recalculation on new data","Re-score when new metrics arrive",["Re-score trigger","Update ranks"])
a("selection","Winner disqualification","Disqualify and promote next",["Disqualify endpoint","Promote next"])
a("selection","Score explanation human-readable","NL explanation of why creative won/lost",["Factor breakdown","English"])
a("selection","Head-to-head comparative scoring","Pairwise creative comparison",["Per-metric win/loss","Overall winner"])
a("selection","Minimum run time enforcement","Prevent early selection",["Min hours config","Clear error"])
a("selection","Auto-extend wait if insufficient data","Extend wait when data insufficient",["Extension config","Max extensions"])
a("selection","Historical winner patterns","Analyze past winners for patterns",["Pattern extraction","Pattern database"])
a("selection","Score calibration across campaigns","Normalize scores for cross-campaign comparison",["Calibration","Baseline"])
a("selection","Winner notification Slack/email","Notify on winner selection",["Slack webhook","Winner summary"])

# AD DEPLOYMENT (20)
a("ads","YouTube Ads integration","Deploy as YouTube Shorts ads via Google Ads API",["API client","Campaign creation","Budget"])
a("ads","Creative format validation per ad platform","Validate video meets ad specs",["Meta specs","TikTok specs","Auto-transcode"])
a("ads","Pixel/conversion tracking setup","Configure Meta/TikTok Pixel",["Pixel ID","Event mapping","Verification"])
a("ads","Retargeting audience creation","Create audience from video viewers",["Viewer audience","Engagement audience"])
a("ads","Lookalike audience creation","Similar audiences from converters",["Source audience","Similarity threshold"])
a("ads","Ad copy A/B within deployment","Multiple copy variants same video",["Multiple ads","Same video","Compare"])
a("ads","Ad dayparting schedule","Ads only during specific hours",["Hour schedule","Day config","Timezone"])
a("ads","Bid strategy selection","Lowest cost/cost cap/bid cap",["Strategy enum","Per-campaign config"])
a("ads","Ad placement selection","Feed/stories/reels/explore/search",["Placement list","Auto vs manual"])
a("ads","Ad preview link generation","Shareable preview before live",["Preview URL","Platform-specific"])
a("ads","Ad approval status monitoring","Monitor review and alert rejections",["Poll status","Rejection alert"])
a("ads","Daily budget monitoring","Track spend vs budget daily",["Daily tracking","80% alert"])
a("ads","Lifetime budget enforcement","Auto-pause at lifetime limit",["Running total","Auto-pause"])
a("ads","Ad spend alert system","Alert on spend threshold breach",["Threshold config","Alert","Auto-pause option"])
a("ads","Cost per acquisition tracking","CPA per creative and campaign",["CPA calc","Trend","Comparison"])
a("ads","Ad fatigue detection","Detect declining CTR over time",["7-day trend","Significance","Threshold"])
a("ads","Ad creative refresh scheduling","Replace fatigued ads with new creatives",["Fatigue trigger","New creative","Auto-swap"])
a("ads","Conversion window configuration","1-day/7-day/28-day click windows",["Window config","Recalculation"])
a("ads","Ad account balance check","Verify balance before deploying",["Balance API","Min threshold"])
a("ads","Bulk ad pause/resume","Pause/resume all ads in round/campaign",["Bulk op","Transaction","Status update"])

# ITERATION (15)
a("iteration","Full angle pivot variation","New angles inspired by winners",["New angles","Inspired-by tracking"])
a("iteration","Visual style iteration","Different styles on winning scripts",["Style param","Same script"])
a("iteration","Script length variants","5s/15s/30s/60s versions",["Duration variants","Script trimming"])
a("iteration","Pacing variation fast/slow","Different editing paces",["Pace param","Scene duration"])
a("iteration","Music/audio swap on winner","Different music on same video",["Library selection","FFmpeg replace"])
a("iteration","Text overlay style variants","Different fonts/colors/animations",["Font variants","Color schemes"])
a("iteration","Thumbnail variation testing","Different thumbnails for same video",["Multiple thumbs","CTR comparison"])
a("iteration","Audience iteration same creative","Same video different audiences",["Audience variants","Per-audience perf"])
a("iteration","Platform-specific iteration","Platform-optimized versions",["Platform editing","Aspect ratio"])
a("iteration","Winning pattern persistence","Store patterns for future campaigns",["Pattern schema","Search by niche"])
a("iteration","Diminishing returns detection","Stop when iterations plateau",["Score delta","Threshold","Recommend stop"])
a("iteration","Max lineage depth enforcement","Limit generation depth",["Max depth","Enforce","Recommend fresh"])
a("iteration","Cross-campaign learning","Apply patterns across campaigns",["Pattern matching","Transfer scoring"])
a("iteration","Diversity scoring between variations","Ensure variations are different enough",["Similarity metric","Min threshold"])
a("iteration","Genealogy tree visualization data","Structured JSON for UI tree rendering",["Tree JSON","Scores per node"])

# INTEGRATION (13)
a("integration","Landing page URL validation","Verify URL returns 200",["HTTP check","SSL","Redirect follow"])
a("integration","UTM parameter auto-generation","Unique UTMs per creative",["utm_source/medium/campaign/content"])
a("integration","Multi-offer campaign support","Test multiple offers in one campaign",["Offer rotation","Compare offers"])
a("integration","Dynamic landing page per creative","Unique LP variants per creative",["URL params","Tracking"])
a("integration","Offer expiry handling","Auto-pause on expired offers",["Expiry check","Auto-pause"])
a("integration","Funnel tracking click→land→convert","Full funnel attribution",["Click","Landing","Conversion"])
a("integration","Revenue tracking per creative","Revenue attributed to each creative",["Revenue import","Attribution"])
a("integration","Supabase auth for API","JWT authentication on endpoints",["JWT validation","401 handling"])
a("integration","External webhook receiver","Receive ad platform webhooks",["Endpoint","Signature verify","Routing"])
a("integration","Conversion pixel verification","Verify pixel on landing page",["Detection script","Alert on missing"])
a("integration","A/B landing page testing","Different LPs per creative",["LP variants","Assignment","Compare"])
a("integration","Social account OAuth management","Token storage/refresh/rotation",["Token storage","Auto-refresh"])
a("integration","External analytics webhook","Send events to PostHog/Mixpanel",["Event schema","Dispatch","Batch"])

# API (18)
a("api","API authentication middleware","JWT/API key auth on all endpoints",["Auth middleware","401 handling"])
a("api","API rate limiting","Per-client rate limits",["Config","429 response","Retry-After"])
a("api","Pagination on all list endpoints","Cursor or offset pagination",["Page size","Cursors","Total count"])
a("api","Filter/sort on campaigns list","Status/mode/date filters, sort options",["Filters","Sort field/direction"])
a("api","Filter/sort on creatives list","Score/source/winner filters",["Filters","Sort options"])
a("api","Bulk operations endpoint","Batch create/update/delete",["Batch format","Transaction","Partial success"])
a("api","Webhook configuration CRUD","Configure webhook URLs via API",["List/Create/Update/Delete"])
a("api","Data export endpoint","CSV/JSON export with filters",["Format selection","Date range","Streaming"])
a("api","API error standardization","Consistent error schema",["Error code","Message","Details"])
a("api","API request validation Pydantic","Strict validation with helpful errors",["Pydantic models","422","Field errors"])
a("api","API response caching","Cache reads with TTL/ETag",["Cache-Control","ETag","Invalidation"])
a("api","API health check endpoint","/api/actp/health with dependency checks",["DB check","External API","Version"])
a("api","OpenAPI/Swagger documentation","Auto-generated from FastAPI",["Swagger UI","OpenAPI spec","Examples"])
a("api","Request logging middleware","Log method/path/status/duration",["Structured log","Duration","Request ID"])
a("api","Long-running task status endpoint","Poll async job status",["Task registry","Progress","Result"])
a("api","Campaign comparison endpoint","Compare two campaigns side-by-side",["Metric delta","Winner per metric"])
a("api","Round comparison endpoint","Track improvement across iterations",["Round delta","Score trend"])
a("api","Creative performance timeline","Time-series data for charting",["Metric filter","Granularity","Chart format"])

# TESTING (20)
a("testing","Unit tests - Creative Engine briefs","Test brief gen/parsing/errors",["Format valid","Error handling"])
a("testing","Unit tests - Publisher caption building","Caption format/limits/hashtags",["Format","Limits","Platform diffs"])
a("testing","Unit tests - Ad Deployer audience","Audience construction from config",["Format","Defaults","Overrides"])
a("testing","Unit tests - Iteration element extraction","Extraction from various configs",["Counts","Ordering","Empty handling"])
a("testing","Unit tests - Offer Connector","URL fetch/error/campaign building",["URL construction","Error handling"])
a("testing","Unit tests - Scheduler progression","Auto-advance logic per state",["Wait check","Auto-collect","Auto-select"])
a("testing","Unit tests - Config merging","Partial override + default preservation",["Partial","Full default","Type safety"])
a("testing","Integration test - Create→Start→Generate","Campaign through generation",["API calls","States verified","DB records"])
a("testing","Integration test - Publish→Collect→Select","Publishing through winner selection",["Publish flow","Metrics","Selection"])
a("testing","Integration test - Ad deploy→Metrics→Scale","Ad deploy through scaling",["Deploy","Metrics","Scale/pause"])
a("testing","Integration test - Full iteration cycle","Generate→Publish→Select→Iterate→Repeat",["Multi-round","State chain","Winners promoted"])
a("testing","E2E test - Complete 3-round campaign","Full campaign from create to completion",["3 rounds","Organic+Ad+Iterate","Completion"])
a("testing","API endpoint tests - All CRUD operations","Test every API endpoint",["All methods","Auth","Validation"])
a("testing","Database migration test","Apply and rollback migration",["Apply clean","Rollback","Idempotent"])
a("testing","Mock external service layer","Test doubles for Sora/YouTube/TikTok/Meta",["Service mocks","Configurable responses"])
a("testing","Test fixtures/factories","Factory functions for test data",["Campaign factory","Creative factory","Post factory"])
a("testing","Performance benchmark tests","Benchmark scoring/selection with large datasets",["1000 creatives","Scoring < 1s"])
a("testing","Error recovery tests","Test retry/timeout/circuit breaker logic",["Retry behavior","Timeout handling"])
a("testing","Concurrent campaign tests","Multiple campaigns running simultaneously",["Parallel execution","No interference"])
a("testing","Test coverage threshold 80%","Enforce minimum test coverage",["Coverage config","CI enforcement","HTML report"])

# SECURITY (10)
a("security","Input sanitization on all endpoints","Prevent XSS/injection in stored data",["Sanitize HTML","SQL param binding","Content validation"])
a("security","Secrets management via env vars","All API keys/tokens from env only",["No hardcoded secrets","Env validation on startup"])
a("security","Credential rotation handling","Graceful handling of rotated tokens",["Auto-refresh","Rotation detection","Re-auth flow"])
a("security","Access control per campaign","Campaign ownership/sharing permissions",["Owner field","Permission check","403 on unauthorized"])
a("security","Audit log for all API actions","Log all mutations with actor/timestamp",["Action log table","Actor tracking","Query endpoint"])
a("security","Request size limits","Max request body size to prevent abuse",["Size limit config","413 response","File upload limits"])
a("security","File upload validation","Validate video files: type/size/duration",["MIME check","Size limit","Duration limit"])
a("security","URL validation for video downloads","Validate URLs before downloading",["Scheme check","Domain allowlist","Timeout"])
a("security","Secure error messages","No stack traces or internal details in errors",["Generic messages","Internal logging","Error codes"])
a("security","CORS configuration","Whitelist allowed origins for API",["Origin whitelist","Preflight handling","Credentials"])

# MONITORING (12)
a("monitoring","Pipeline health dashboard data","Service status and dependency checks",["DB status","External APIs","Queue depth"])
a("monitoring","Error rate tracking per module","Track error counts per service",["Per-module counters","Error rate %","Alerting"])
a("monitoring","Latency tracking per pipeline step","Duration of each step in the pipeline",["Step timing","P95 latency","Bottleneck detection"])
a("monitoring","Cost tracking per campaign","Total cost: generation + ad spend + API calls",["Cost breakdown","Running total","Budget vs actual"])
a("monitoring","Cost alerting on thresholds","Alert when costs exceed configured limits",["Threshold config","Alert trigger","Auto-pause option"])
a("monitoring","External API health monitoring","Monitor Sora/YouTube/TikTok/Meta availability",["Health pings","Status tracking","Degradation handling"])
a("monitoring","Stale campaign detection","Detect campaigns stuck with no progress",["Stale threshold","Alert","Auto-pause option"])
a("monitoring","Structured logging with correlation IDs","Request-scoped log correlation",["Correlation ID","Propagation","Log aggregation"])
a("monitoring","Queue depth monitoring","Track generation/publish queue sizes",["Queue size metric","Alert on backlog"])
a("monitoring","Uptime tracking for pipeline","Track pipeline availability %",["Uptime calc","Downtime events","SLA %"])
a("monitoring","Deployment tracking","Track deploys and correlate with metrics",["Deploy markers","Version tracking"])
a("monitoring","Dead letter queue for failed jobs","Capture permanently failed jobs for review",["DLQ table","Retry from DLQ","Manual review"])

# UI (16)
a("ui","Creative preview video player","Inline video player with controls",["Play/pause","Seek","Fullscreen"])
a("ui","Metric charts line/bar","Interactive charts for performance data",["Line chart","Bar chart","Tooltip"])
a("ui","Round timeline visualization","Visual timeline of round progression",["State indicators","Duration","Active highlight"])
a("ui","Creative genealogy tree view","Interactive tree showing creative lineage",["Tree layout","Expand/collapse","Score coloring"])
a("ui","Budget allocation pie chart","Spend breakdown by platform/creative",["Pie chart","Labels","Interactive"])
a("ui","Platform breakdown chart","Performance split by platform",["Stacked bar","Platform colors","Comparison"])
a("ui","Winner badge/highlighting","Visual indicator for winning creatives",["Badge icon","Score display","Rank number"])
a("ui","Real-time status indicators","Live status dots for campaign/round states",["Color coding","Pulse animation","Auto-refresh"])
a("ui","Filter/search on all lists","Client-side filter + server search",["Debounced search","Multi-filter","Clear filters"])
a("ui","Mobile responsive layout","Dashboard usable on mobile devices",["Responsive grid","Touch interactions","Mobile nav"])
a("ui","Export to PDF report","Generate downloadable campaign report",["PDF generation","Charts included","Summary stats"])
a("ui","Loading/skeleton states","Skeleton loaders while data fetches",["Skeleton components","Shimmer animation","Error state"])
a("ui","Empty state designs","Informative empty states with CTAs",["No campaigns","No creatives","Get started"])
a("ui","Settings page","Pipeline configuration UI",["Default config","Per-campaign overrides","Save/reset"])
a("ui","Notification center","In-app notifications for events",["Event list","Read/unread","Click to navigate"])
a("ui","Keyboard shortcuts","Quick actions via keyboard",["? for help","N for new","P for pause"])

def main():
    with open(FL) as f:
        data = json.load(f)
    existing = data["features"]
    idx = 76
    for cat, name, desc, crit in NEW:
        existing.append({
            "id": f"ACTP-{idx:03d}",
            "name": name,
            "description": desc,
            "category": cat,
            "priority": "P1",
            "passes": False,
            "effort": "4h",
            "criteria": crit,
        })
        idx += 1
    data["features"] = existing
    with open(FL, "w") as f:
        json.dump(data, f, indent=2)
    total = len(existing)
    passing = sum(1 for f in existing if f["passes"])
    print(f"Total: {total} features ({passing} passing, {total-passing} pending)")
    cats = {}
    for f in existing:
        cats[f["category"]] = cats.get(f["category"], 0) + 1
    for c, n in sorted(cats.items(), key=lambda x: -x[1]):
        print(f"  {c}: {n}")

if __name__ == "__main__":
    main()
