#!/usr/bin/env python3
"""Generate ~300 features per Rork app. Run this script directly."""
import json, os, sys

BASE = '/Users/isaiahdupree/Documents/Software'

# Import common features
sys.path.insert(0, os.path.dirname(__file__))
from gen300_common import COMMON

def gen_entity_features(prefix, entities, domain_extras):
    """Generate ~145 app-specific features from entities + domain extras."""
    F = []
    idx = 1
    
    def add(cat, pri, desc, crit):
        nonlocal idx
        F.append((f"{prefix}-{idx:03d}", cat, pri, desc, crit))
        idx += 1

    # Per-entity DB tables (2 per entity)
    for e in entities:
        t = e.lower().replace(" ","_")
        add("database", 1, f"Create {t}s table with full schema and RLS", [f"id UUID PK", f"user_id FK", f"All {e} fields", "timestamps", "RLS policies"])
        add("database", 2, f"Create {t}_history table for audit trail", [f"FK to {t}s", "action type", "changed_fields JSONB", "created_at"])
    
    # Standard DB extras
    for d, c in [
        ("Create saved_filters table for custom views", ["user_id, name, filter_config JSONB"]),
        ("Create export_jobs table for async exports", ["user_id, type, status, file_url"]),
        ("Create user_app_settings table", ["user_id, settings JSONB, defaults"]),
        ("Create notifications_log table", ["user_id, type, title, body, read_at"]),
        ("Create file_uploads table with Storage refs", ["user_id, bucket, path, size, mime_type"]),
        ("Create feature_flags table for remote config", ["flag_name, enabled, rollout_pct", "per-user overrides"]),
        ("Create feedback table for user feedback", ["user_id, category, message", "screenshot_url, status"]),
        ("Create search_history table for recent searches", ["user_id, query, entity_type", "created_at"]),
    ]:
        add("database", 2, d, c)

    # Per-entity CRUD + search + validation + sort + export (5 per entity)
    for e in entities:
        add("api", 1, f"Implement {e} create with validation", [f"Required fields check", "Format validation", "Unique constraints", "Return created"])
        add("api", 1, f"Implement {e} read (list with pagination + detail)", ["Cursor pagination", "Include relations", "Single by ID"])
        add("api", 1, f"Implement {e} update with partial fields", ["Partial update", "Validation", "Optimistic locking"])
        add("api", 1, f"Implement {e} soft delete and restore", ["Set status=deleted", "Filter in queries", "Restore endpoint"])
        add("api", 2, f"Implement {e} search with full-text and filters", ["tsvector search", "Multi-field filter", "Sort options", "Ranked results"])

    # Standard API features
    for d, c in [
        ("Implement real-time updates via Supabase Realtime", ["Subscribe to tables", "Handle INSERT/UPDATE/DELETE", "Update local state"]),
        ("Implement activity logging for all mutations", ["Log action type", "Entity reference", "User attribution"]),
        ("Implement batch create/update/delete operations", ["Accept arrays", "Transaction wrapper", "Progress callback"]),
        ("Implement tagging system across entities", ["Create/manage tags", "Apply to any entity", "Filter by tag"]),
        ("Implement favorites/bookmarks system", ["Toggle favorite", "List favorites", "Sort by favorited"]),
        ("Implement data export to JSON and CSV", ["Select entities/fields", "Generate file", "Share/download"]),
        ("Implement data import from CSV with mapping", ["File upload", "Column mapping UI", "Validation", "Duplicate handling"]),
        ("Implement sharing via generated links", ["Generate share URL", "View/edit permissions", "Expiry option"]),
        ("Implement dashboard summary statistics", ["Key metrics aggregation", "Period comparison", "Trend data"]),
        ("Implement notification triggers for key events", ["Define rules", "Create notifications", "Push delivery"]),
        ("Implement AI-powered suggestions", ["OpenAI/Claude integration", "Context-aware", "Accept/reject"]),
        ("Implement sorting preferences persistence", ["Save per-list sort", "Restore on load"]),
        ("Implement usage analytics per user", ["Action counts", "Feature usage", "Export"]),
        ("Implement rate limiting for heavy operations", ["Per-user limits", "Per-tier limits", "Graceful error"]),
        ("Implement data backup to JSON", ["Full user data export", "Selective backup", "GDPR compliance"]),
        ("Implement webhook outgoing for integrations", ["Events trigger webhooks", "Retry logic", "Payload signing"]),
        ("Implement recent search history tracking", ["Save searches", "Show recent", "Clear history"]),
        ("Implement feature flag checking for remote config", ["Fetch flags on launch", "Cache locally", "Override per user"]),
        ("Implement data migration helpers for schema changes", ["Detect schema version", "Run migration", "Verify integrity"]),
        ("Implement feedback submission to Supabase", ["Category selection", "Message + screenshot", "Confirmation"]),
        ("Implement entity duplication/clone functionality", ["Deep copy entity", "Rename clone", "Preserve relations"]),
        ("Implement undo/redo for recent mutations", ["Track last N actions", "Undo API", "Redo API", "Timeout window"]),
        ("Implement entity archival (hide without delete)", ["Archive toggle", "Filter archived", "Restore from archive"]),
        ("Implement user-specific onboarding progress tracking", ["Track steps completed", "Resume where left off", "Skip option"]),
    ]:
        add("api", 2, d, c)

    # Domain-specific extras
    for cat, items in domain_extras.items():
        for d, c in items:
            add(cat, 2, d, c)

    # Per-entity UI screens (3 per entity: list, detail, form)
    for e in entities:
        add("ui", 1, f"Create {e} list screen with search and filters", ["FlashList", "Search bar", "Filter chips", "Sort", "Pull refresh"])
        add("ui", 1, f"Create {e} detail screen", ["All fields", "Edit/delete actions", "Related items", "Activity log"])
        add("ui", 2, f"Create {e} create/edit form screen", ["All fields with validation", "Save/cancel buttons", "Loading state"])

    # Standard UI screens
    for d, c in [
        ("Create home dashboard with key metrics and quick actions", ["Summary cards", "Recent items", "Quick action FAB"]),
        ("Create search/filter results screen", ["Combined results", "Category tabs", "Highlight matches"]),
        ("Create statistics/analytics dashboard with charts", ["Line/bar/pie charts", "Period selector", "Key metrics"]),
        ("Create activity/history timeline screen", ["Chronological events", "Filter by type", "Tap for detail"]),
        ("Create batch action toolbar for multi-select", ["Selection mode", "Bulk actions", "Count display"]),
        ("Create share/export screen", ["Format selection", "Preview", "Share/download"]),
        ("Create import wizard screen", ["File upload", "Mapping", "Preview", "Progress"]),
        ("Create favorites/bookmarks screen", ["List favorites", "Remove", "Navigate"]),
        ("Create tag management screen", ["Tag list", "Create/edit/delete", "Color picker"]),
        ("Create notification center screen", ["Notification list", "Read/unread", "Tap to navigate"]),
        ("Create empty states for all list screens", ["Illustration", "Helpful text", "Action button"]),
        ("Create loading skeletons for all screens", ["Skeleton layout", "Shimmer animation"]),
        ("Create error states for all screens", ["Error message", "Retry button"]),
        ("Create app-specific settings screen section", ["Domain preferences", "Display options", "Data management"]),
        ("Create walkthrough/tutorial overlay for key features", ["Step-by-step tooltips", "Skip option", "Show once"]),
        ("Create pull-to-refresh on all list screens", ["Refresh indicator", "Reload data", "Show updated toast"]),
        ("Create swipe-to-delete on list items", ["Swipe gesture", "Delete confirmation", "Undo option"]),
        ("Create sorting modal with multiple options", ["Sort fields", "Asc/desc toggle", "Apply/reset"]),
        ("Create advanced filter sheet with date ranges", ["Date pickers", "Range filters", "Multiple criteria"]),
        ("Create data visualization chart components", ["Line chart", "Bar chart", "Pie chart", "Responsive sizing"]),
        ("Create drag-to-reorder for custom ordering", ["Long-press to activate", "Drag handles", "Save order"]),
        ("Create context menu on long-press for items", ["Edit, Delete, Share, Archive", "Platform-native feel"]),
        ("Create keyboard shortcuts for power users (iPad)", ["Cmd+N new", "Cmd+S save", "Cmd+F search"]),
        ("Create split-view layout for iPad/tablet", ["Master-detail layout", "Responsive breakpoints"]),
        ("Create offline mode indicator and cached data display", ["Offline badge", "Cached data notice", "Sync button"]),
        ("Create undo toast after destructive actions", ["Undo button", "Countdown timer", "Auto-dismiss"]),
    ]:
        add("ui", 2, d, c)

    # Testing
    for e in entities:
        add("testing", 3, f"Unit tests for {e} CRUD operations", ["Create", "Read", "Update", "Delete", "Validation"])
        add("testing", 3, f"Unit tests for {e} business logic", ["Edge cases", "Calculations", "Rules"])
    for d, c in [
        ("Integration tests for primary user workflow", ["Create > Edit > List > Delete > Export"]),
        ("E2E test for onboarding through first action", ["Sign up > Onboard > First create > Verify"]),
        ("Performance test for list with 500+ items", ["Scroll speed", "Search speed", "Filter speed"]),
        ("Integration tests for import/export flow", ["Upload > Map > Preview > Import > Verify"]),
        ("Unit tests for AI suggestion accuracy", ["Context building", "Response parsing", "Fallback handling"]),
        ("Integration tests for real-time updates", ["Create > Verify update received > UI reflects"]),
        ("Unit tests for data validation rules", ["Required fields", "Format validation", "Edge cases"]),
        ("Unit tests for pagination logic", ["First page", "Next page", "Empty page", "Total count"]),
        ("Integration tests for auth-protected routes", ["Unauthenticated redirect", "Authenticated access", "Token refresh"]),
        ("Integration tests for subscription tier gating", ["Free user blocked", "Pro user access", "Upgrade prompt"]),
        ("Accessibility audit: screen reader compatibility", ["Labels on all buttons", "Roles set", "Focus order"]),
        ("Performance test: app cold start time < 3s", ["Measure startup", "Optimize heavy imports", "Lazy load"]),
    ]:
        add("testing", 3, d, c)

    return F

# ============================================================
# APP DEFINITIONS (entities + domain extras)
# ============================================================
APPS = {
    "rork-crm-superwall": ("CRM", "AI-Enhanced Personal CRM", "rork-crm",
        ["Contact", "Interaction", "MessageTemplate", "Goal", "Group", "Reminder"],
        {"domain": [
            ("Implement warmth score decay algorithm", ["Decay -1/day", "Boost +10-30", "Cap 0-100", "Configurable"]),
            ("Implement device contacts import via expo-contacts", ["Permission request", "Read contacts", "Merge duplicates", "Field mapping"]),
            ("Implement AI message generation with OpenAI/Claude", ["Contact context", "Tone selection", "Multiple suggestions"]),
            ("Implement AI relationship insights and weekly digest", ["Pattern analysis", "Neglected contacts", "Summary generation"]),
            ("Implement birthday/anniversary reminder scheduling", ["Detect upcoming", "Push notifications", "Advance notice config"]),
            ("Implement contact deduplication and merge", ["Fuzzy matching", "Merge suggestions", "One-click merge"]),
            ("Implement vCard import/export", ["Parse .vcf", "Generate .vcf", "Batch support"]),
            ("Implement contact warmth push notification alerts", ["Threshold alerts", "Configurable per contact"]),
            ("Implement relationship map network visualization", ["Graph view", "Connection lines", "Tap to navigate"]),
            ("Implement template variable substitution engine", ["{{first_name}}, {{company}}", "Preview with data", "Custom vars"]),
            ("Implement contact timeline aggregation", ["Interactions + notes + reminders", "Chronological", "Filterable"]),
            ("Implement smart suggestions: who to contact next", ["Warmth decay based", "Goal based", "Pattern based"]),
            ("Create warmth gauge visualization component", ["Color-coded arc", "Score number", "Trend arrow"]),
            ("Create AI message composer screen", ["Contact context display", "Tone selector", "Preview/edit", "Copy/share"]),
            ("Create relationship map interactive view", ["Pinch zoom", "Tap contact", "Drag to rearrange"]),
            ("Create weekly digest notification and screen", ["Activity summary", "Warmth changes", "Action suggestions"]),
        ]}),
    "kawaii-coffee-timer": ("COF", "Kawaii Coffee Timer", "kawaii-coffee",
        ["BrewMethod", "BrewSession", "CoffeeBean", "CustomPreset", "Achievement"],
        {"domain": [
            ("Implement multi-step brew timer engine", ["Countdown per step", "Audio/haptic alerts", "Pause/resume", "Auto-advance"]),
            ("Implement brew statistics calculation", ["Total brews", "Favorite method", "Rating trends", "Streak"]),
            ("Implement bean recommendation by method", ["Method-bean compatibility", "Roast level matching"]),
            ("Implement caffeine tracking per brew", ["Estimate mg per method", "Daily total", "Limit warnings"]),
            ("Implement grind size guide per method", ["Visual reference", "Adjustable recommendations"]),
            ("Implement water ratio calculator", ["Input coffee or water", "Auto-calculate", "Ratio slider"]),
            ("Implement community preset sharing", ["Publish publicly", "Browse/download", "Rate presets"]),
            ("Implement achievement unlock system", ["Criteria checking", "Progress tracking", "Notifications"]),
            ("Implement streak tracking with push reminders", ["Daily streak", "Milestone celebrations"]),
            ("Implement share card generation for social", ["Brew result image", "Method/rating info", "App link"]),
            ("Implement flavor wheel tasting notes", ["Interactive wheel", "Select flavors", "Save with session"]),
            ("Implement kawaii character animations during brew", ["Watch brew", "Celebrate completion"]),
            ("Implement pour-over pattern timer", ["Bloom phase", "Pour intervals", "Visual guide"]),
            ("Implement bean origin world map", ["Countries/regions", "Tap for beans", "Flavor profiles"]),
            ("Create active brew timer screen with animations", ["Large countdown", "Step instructions", "Kawaii visuals"]),
            ("Create kawaii theme shop screen", ["Theme previews", "Purchase to unlock", "Apply/preview"]),
        ]}),
    "rork-voice-chat-pdf": ("PDF", "Voice Chat PDF", "voice-chat-pdf",
        ["PDF", "ChatSession", "Collection", "Bookmark", "Highlight"],
        {"domain": [
            ("Implement PDF text extraction pipeline", ["pdf-parse/pdfjs", "Page-by-page", "OCR for scanned"]),
            ("Implement PDF chunking and embedding generation", ["~500 token chunks", "OpenAI embeddings", "pgvector storage"]),
            ("Implement RAG chat with vector search", ["Similarity search", "Top-K retrieval", "Context building", "AI response"]),
            ("Implement voice-to-text with Whisper API", ["Audio recording", "Transcription", "Multi-language"]),
            ("Implement text-to-speech for AI responses", ["OpenAI TTS/ElevenLabs", "Voice selection", "Speed control"]),
            ("Implement citation linking to PDF pages", ["Page references in response", "Tap to jump", "Highlight source"]),
            ("Implement multi-PDF collection chat", ["Cross-PDF context", "Source attribution"]),
            ("Implement AI-powered PDF summarization", ["Per page/chapter", "Key points", "Save summaries"]),
            ("Implement flashcard generation from PDF content", ["AI extract concepts", "Q&A cards", "Study mode"]),
            ("Implement voice conversation continuous mode", ["Auto-detect speech end", "Auto-play response"]),
            ("Implement PDF page rendering and viewer", ["Render pages", "Zoom/pan", "Thumbnail strip"]),
            ("Implement suggested questions from content", ["AI-generated", "Tap to ask", "Refresh"]),
            ("Implement audio waveform recording UI", ["Waveform animation", "Duration counter"]),
            ("Implement usage tier limits (uploads/messages)", ["Count tracking", "Warn near limit", "Upgrade prompt"]),
            ("Enable pgvector extension for embeddings", ["CREATE EXTENSION vector", "Similarity function"]),
            ("Implement chat context window management", ["Token tracking", "Trim/summarize old context"]),
        ]}),
    "rork-youtube-quiz-generator": ("QZ", "YouTube Quiz Generator", "youtube-quiz",
        ["Quiz", "Question", "UserProgress", "LearningPath", "LeaderboardEntry"],
        {"domain": [
            ("Implement YouTube transcript extraction", ["YouTube API/captions", "Language detection", "Segment parsing"]),
            ("Implement AI quiz generation from transcript", ["OpenAI/Claude", "MC/TF/open questions", "Difficulty calibration"]),
            ("Implement spaced repetition algorithm (SM-2)", ["Ease factor", "Interval calculation", "Review scheduling"]),
            ("Implement quiz sharing via share code", ["Generate code", "Public/private toggle", "View stats"]),
            ("Implement leaderboard per quiz", ["Score ranking", "Time tiebreaker", "Friends filter"]),
            ("Implement video timestamp to question mapping", ["Link question to moment", "Jump to timestamp"]),
            ("Implement quiz difficulty adaptation", ["Track performance", "Auto-adjust difficulty"]),
            ("Implement offline quiz caching", ["Cache locally", "Answer offline", "Sync when online"]),
            ("Implement AI explanation generation per answer", ["Why correct", "Reference transcript", "Additional context"]),
            ("Implement batch quiz generation from playlist", ["Parse playlist", "Quiz per video", "Learning path"]),
            ("Implement daily quiz challenge with streaks", ["Featured daily", "Streak tracking", "Bonus points"]),
            ("Implement certificate generation on high score", ["Score threshold", "Shareable image", "Verification"]),
            ("Implement hint system for difficult questions", ["Progressive hints", "Point deduction", "Transcript reference"]),
            ("Implement quiz review mode after completion", ["All answers", "Correct marking", "Explanations"]),
            ("Create active quiz screen with timer", ["Question display", "Options", "Timer", "Progress bar"]),
            ("Create quiz generation progress animation", ["Transcript step", "Generation step", "Complete"]),
        ]}),
}

# Remaining apps with standard entity patterns
SIMPLE_APPS = [
    ("rork-ai-calculator-builder", "CALC", "AI Calculator Builder", "ai-calculator",
     ["Calculator", "Formula", "CalculationHistory", "SharedCalc"],
     [("Implement NL-to-formula AI generation", ["OpenAI/Claude", "Parse description", "Generate formula"]),
      ("Implement formula parser and evaluator", ["Math expressions", "Variables", "Error handling"]),
      ("Implement unit conversion library", ["SI/Imperial", "Custom units", "Auto-detect"]),
      ("Implement calculator marketplace", ["Publish public", "Browse/fork", "Ratings"]),
      ("Implement formula version history", ["Track changes", "Revert", "Diff view"]),
      ("Implement calculation sharing with deep links", ["Share result", "Recipient can recalculate"]),
      ("Implement widget/shortcut for frequent calcs", ["Quick access", "Recent calculations"]),
      ("Implement graphing/chart output for formulas", ["Plot functions", "Multiple series", "Interactive"]),
      ("Implement input validation per formula variable", ["Type checking", "Range limits", "Units"]),
      ("Implement collaborative calculator editing", ["Share edit access", "Real-time sync"]),
      ("Implement calculator category organization", ["Finance, health, cooking, etc", "Custom categories"]),
      ("Implement template calculators library", ["Pre-built: tip, BMI, mortgage", "Customize from template"]),
      ("Create formula builder drag-and-drop UI", ["Variable blocks", "Operator blocks", "Preview"]),
      ("Create calculation result screen with export", ["Result display", "History save", "Share/copy"]),
      ("Create calculator marketplace browse screen", ["Categories", "Popular", "Search", "Preview"]),
      ("Create graph/chart visualization screen", ["Interactive plot", "Pan/zoom", "Data points"]),
      ("Implement multi-variable calculator forms", ["Dynamic input fields", "Conditional fields", "Grouped sections"]),
      ("Implement calculation history comparison", ["Side-by-side results", "Diff highlight", "Save comparison"]),
      ("Implement calculator embed code generator", ["Responsive iframe", "Custom styling", "Auto-resize"]),
      ("Implement formula explanation with AI", ["Explain each step", "Show intermediate values", "Learning mode"]),
      ("Implement voice input for calculations", ["Whisper API", "Parse numbers/operators", "Confirm before calc"]),
      ("Implement calculator rating and review system", ["Star rating", "Text review", "Sort by rating"]),
      ("Implement saved inputs/presets per calculator", ["Save input sets", "Name presets", "Quick load"]),
      ("Implement calculator usage analytics", ["Times used", "Average inputs", "Popular calculators"]),
      ("Create calculator preview card component", ["Mini preview", "Key inputs shown", "Tap to open"]),
      ("Create formula step-by-step breakdown screen", ["Intermediate steps", "Variable values", "Visual flow"]),
      ("Create voice input overlay for calculations", ["Waveform", "Parsed text preview", "Confirm"]),]),
    ("rork-client-portal-system", "CP", "Client Portal System", "client-portal",
     ["Client", "Project", "Invoice", "Message", "Milestone"],
     [("Implement Stripe payment for invoices", ["Payment links", "Webhooks", "Receipts"]),
      ("Implement PDF invoice generation", ["Template", "Line items", "Tax calc", "Branding"]),
      ("Implement real-time messaging via Realtime", ["Live messages", "Read receipts", "Attachments"]),
      ("Implement email notifications for clients", ["Edge Function", "Invoice sent", "Milestone update"]),
      ("Implement client-facing read-only portal", ["Share link", "No auth needed", "Limited view"]),
      ("Implement project Gantt/timeline view", ["Milestones", "Dependencies", "Progress"]),
      ("Implement recurring invoice automation", ["Schedule", "Auto-generate", "Auto-send"]),
      ("Implement time tracking per project", ["Timer", "Manual entry", "Invoice time"]),
      ("Implement contract/proposal templates", ["Template library", "Variable fill", "PDF export"]),
      ("Implement client onboarding wizard", ["Welcome flow", "Info collection", "First project setup"]),
      ("Implement project status workflow engine", ["Custom statuses", "Transition rules", "Notifications"]),
      ("Implement expense tracking per project", ["Log expenses", "Categories", "Attach receipts"]),
      ("Create invoice builder screen", ["Line items", "Tax", "Preview", "Send"]),
      ("Create project timeline visualization", ["Gantt chart", "Drag milestones", "Dependencies"]),
      ("Create client messaging screen", ["Chat UI", "Attachments", "Typing indicator"]),
      ("Create time tracking screen with timer", ["Start/stop", "Project selector", "Weekly summary"]),]),
    ("rork-collaborative-ai-workos", "WK", "Collaborative AI WorkOS", "collab-ai-workos",
     ["Workspace", "Task", "Document", "Comment", "TeamMember"],
     [("Implement real-time presence indicators", ["Online status", "Viewing indicator", "Typing"]),
      ("Implement AI task breakdown from description", ["Parse requirements", "Create subtasks", "Estimate effort"]),
      ("Implement role-based access control", ["Admin/member/viewer", "Permission checks", "Invite flow"]),
      ("Implement document collaborative editing", ["Real-time sync", "Cursor positions", "History"]),
      ("Implement workspace analytics", ["Task completion rates", "Team velocity", "Burndown"]),
      ("Implement Kanban board view", ["Drag-drop columns", "Card details", "Swimlanes"]),
      ("Implement sprint/iteration planning", ["Create sprints", "Assign tasks", "Velocity tracking"]),
      ("Implement AI meeting notes summarizer", ["Input transcript", "Extract actions", "Create tasks"]),
      ("Implement workspace templates", ["Pre-built templates", "Custom templates", "Clone"]),
      ("Implement team chat per workspace", ["Real-time messaging", "Thread replies", "Mentions"]),
      ("Implement file sharing per workspace", ["Upload files", "Organize folders", "Preview"]),
      ("Implement task dependency management", ["Define dependencies", "Block visualization", "Auto-reschedule"]),
      ("Create Kanban board screen", ["Columns", "Drag-drop", "Quick add"]),
      ("Create workspace dashboard", ["Team activity", "Task metrics", "Calendar"]),
      ("Create team management screen", ["Members list", "Roles", "Invite/remove"]),
      ("Create document editor screen", ["Rich text", "Collaborative cursors", "Autosave"]),]),
    ("rork-couples-habit-tracker", "CH", "Couples Habit Tracker", "couples-habits",
     ["Habit", "HabitLog", "Partner", "Challenge", "Reward"],
     [("Implement partner linking via invite code", ["Generate code", "Accept flow", "Shared data"]),
      ("Implement partner nudge/remind feature", ["Push to partner", "Custom message", "Cooldown"]),
      ("Implement shared challenges between partners", ["Create challenge", "Both participate", "Winner"]),
      ("Implement reward system for milestones", ["Define rewards", "Unlock on achievement"]),
      ("Implement shared calendar view", ["Both partners habits", "Color-coded", "Completion"]),
      ("Implement habit suggestion engine", ["Popular habits", "AI suggestions", "Categories"]),
      ("Implement mood tracking correlated with habits", ["Daily mood", "Correlation analysis", "Insights"]),
      ("Implement relationship milestone tracking", ["Anniversaries", "Streak milestones"]),
      ("Implement daily/weekly habit reminders", ["Configurable times", "Partner completion notify"]),
      ("Implement habit streak calculations", ["Current streak", "Best streak", "Freeze days"]),
      ("Implement habit completion animations", ["Check animation", "Streak fire", "Partner celebration"]),
      ("Implement habit analytics dashboard", ["Completion rates", "Trends", "Partner comparison"]),
      ("Create partner dashboard screen", ["Both habits", "Streaks", "Challenges"]),
      ("Create habit completion calendar heatmap", ["Daily grid", "Intensity colors", "Both partners"]),
      ("Create challenge creation and tracking screen", ["Set challenge", "Progress", "Results"]),
      ("Create mood/habit correlation insights screen", ["Charts", "Correlations", "Tips"]),]),
    ("rork-ig-research---lead-finder", "IG", "IG Research and Lead Finder", "ig-lead-finder",
     ["Lead", "SearchQuery", "Campaign", "OutreachTemplate", "Tag"],
     [("Implement Instagram profile data fetching", ["API/scraping service", "Rate limiting", "Proxy"]),
      ("Implement lead scoring algorithm", ["Engagement rate", "Followers", "Niche relevance", "Growth"]),
      ("Implement AI niche analysis", ["Competitor mapping", "Content gaps", "Audience overlap"]),
      ("Implement outreach template system", ["Variable templates", "A/B variants", "Track performance"]),
      ("Implement campaign funnel tracking", ["Stages: found>contacted>responded", "Conversion rates"]),
      ("Implement hashtag research tool", ["Related hashtags", "Volume estimation", "Competition"]),
      ("Implement bulk lead import/export CSV", ["Column mapping", "Deduplication", "CRM format"]),
      ("Implement lead list segmentation", ["Dynamic segments", "Multi-criteria", "Auto-update"]),
      ("Implement outreach scheduling", ["Schedule messages", "Optimal timing", "Follow-up sequences"]),
      ("Implement engagement rate calculator", ["Likes/comments/followers formula", "Benchmark comparison"]),
      ("Implement competitor tracking dashboard", ["Track accounts", "Growth comparison", "Content analysis"]),
      ("Implement lead pipeline Kanban view", ["Drag between stages", "Quick actions", "Filters"]),
      ("Create lead pipeline Kanban screen", ["Columns by stage", "Drag-drop", "Count per stage"]),
      ("Create lead detail screen with IG profile", ["Profile preview", "Metrics", "Outreach history"]),
      ("Create hashtag explorer screen", ["Search", "Related", "Volume charts"]),
      ("Create campaign analytics screen", ["Funnel visualization", "Conversion rates", "ROI"]),]),
    ("rork-learning-to-gigs-app", "LG", "Learning-to-Gigs", "learning-gigs",
     ["Skill", "Gig", "LearningPath", "Portfolio", "Earning"],
     [("Implement skill assessment quiz engine", ["Quiz per skill", "Proficiency scoring"]),
      ("Implement AI learning path generation", ["OpenAI/Claude curriculum", "Resources", "Milestones"]),
      ("Implement gig platform API hooks", ["Fiverr/Upwork matching", "Rate comparison"]),
      ("Implement portfolio builder with share link", ["Showcase skills", "Custom URL"]),
      ("Implement earnings dashboard", ["By gig/skill", "Trends", "Tax estimation"]),
      ("Implement skill-to-gig matching algorithm", ["Map skills to platforms", "Rate estimation"]),
      ("Implement goal setting with AI coaching", ["Income goals", "Progress tracking"]),
      ("Implement skill marketplace trends data", ["In-demand skills", "Rate trends"]),
      ("Implement certificate generation", ["Proof of level", "Shareable badge"]),
      ("Implement time logging per gig", ["Start/stop timer", "Manual entry", "Invoice"]),
      ("Implement client management per gig", ["Client info", "Communication log"]),
      ("Implement proposal template system", ["Templates", "Variable fill", "Track sent"]),
      ("Create skill radar chart visualization", ["Multi-axis", "Progress over time"]),
      ("Create gig tracker board", ["Pipeline stages", "Earnings per gig"]),
      ("Create learning path progress screen", ["Milestones", "Resources", "Completion"]),
      ("Create earnings analytics dashboard", ["Monthly/yearly", "By skill", "Projections"]),]),
    ("rork-media-ai-schema---app", "MAS", "Media AI Schema", "media-ai-schema",
     ["MediaAsset", "Schema", "AITag", "Collection", "ProcessingJob"],
     [("Implement AI auto-tagging with vision API", ["OpenAI Vision", "Object detection", "Classification"]),
      ("Implement vector embedding semantic search", ["Image embeddings", "pgvector", "Similarity"]),
      ("Implement batch media processing queue", ["Upload queue", "Background processing", "Progress"]),
      ("Implement schema template system", ["Define fields", "Apply to assets", "Validate"]),
      ("Implement media format conversion", ["Resize/compress images", "Video transcode"]),
      ("Implement duplicate detection via perceptual hash", ["pHash", "Threshold", "Group dupes"]),
      ("Implement face detection and grouping", ["Detect faces", "Cluster by person"]),
      ("Implement EXIF/metadata extraction", ["Camera settings", "GPS", "Date"]),
      ("Implement smart album auto-creation", ["By content type", "By date", "By location"]),
      ("Implement media gallery grid with zoom", ["Pinch zoom", "Lightbox view", "Swipe through"]),
      ("Implement bulk tag editing", ["Select multiple", "Apply/remove tags", "Auto-tag batch"]),
      ("Implement storage quota management per tier", ["Track usage", "Warn near limit", "Cleanup tools"]),
      ("Create media gallery grid screen", ["Thumbnails", "Zoom", "Select mode"]),
      ("Create AI tag editor screen", ["Tag suggestions", "Accept/reject", "Manual add"]),
      ("Create schema builder screen", ["Define fields", "Preview", "Apply to assets"]),
      ("Create processing queue status screen", ["Jobs list", "Progress bars", "Retry failed"]),]),
    ("rork-meta-content-growth-hub", "MCG", "Meta Content Growth Hub", "meta-growth-hub",
     ["ContentPiece", "GrowthMetric", "Strategy", "Schedule", "Competitor"],
     [("Implement Meta Graph API OAuth and fetch", ["OAuth flow", "Page insights", "Post metrics"]),
      ("Implement AI content strategy generation", ["Best times", "Content recs", "Hashtags"]),
      ("Implement competitor benchmarking", ["Track pages", "Compare metrics", "Gap analysis"]),
      ("Implement content calendar scheduling", ["Plan posts", "Set schedule", "Reminders"]),
      ("Implement A/B content testing", ["Create variants", "Split audience", "Track"]),
      ("Implement viral pattern detection", ["High-engagement analysis", "Pattern matching"]),
      ("Implement audience insight analysis", ["Demographics", "Active hours", "Interests"]),
      ("Implement ROI calculator for content", ["Cost per post", "Engagement value"]),
      ("Implement best posting time AI analysis", ["Historical data", "Engagement patterns"]),
      ("Implement hashtag performance tracking", ["Usage count", "Engagement lift", "Trending"]),
      ("Implement content repurposing suggestions", ["AI analyze content", "Format suggestions"]),
      ("Implement growth forecast with AI", ["Trend extrapolation", "Scenario modeling"]),
      ("Create content calendar screen", ["Calendar view", "Drag to schedule", "Status colors"]),
      ("Create growth analytics dashboard", ["Follower trend", "Engagement trend", "Benchmarks"]),
      ("Create competitor comparison screen", ["Side-by-side metrics", "Growth comparison"]),
      ("Create AI strategy recommendations screen", ["Suggestions list", "Accept/schedule", "Track results"]),]),
    ("rork-promap-rf-indoor-mapper", "RF", "ProMap RF Indoor Mapper", "promap-rf",
     ["FloorPlan", "ScanPoint", "HeatMap", "AccessPoint", "Report"],
     [("Implement WiFi signal scanning", ["Device APIs", "Signal strength", "Multi-network"]),
      ("Implement heatmap interpolation algorithm", ["IDW interpolation", "Color gradient", "Resolution"]),
      ("Implement floor plan image annotation", ["Draw walls", "Place APs", "Label zones"]),
      ("Implement scan report PDF generation", ["Heatmap overlay", "Statistics", "Recommendations"]),
      ("Implement AP detection and identification", ["SSID, BSSID", "Channel, frequency", "Manufacturer"]),
      ("Implement multi-floor support", ["Floor selector", "Elevator/stair connections"]),
      ("Implement signal prediction modeling", ["Wall attenuation", "Distance falloff", "Interference"]),
      ("Implement coverage zone classification", ["Excellent/good/fair/poor", "Dead zone detection"]),
      ("Implement before/after comparison", ["Overlay two scans", "Improvement highlighting"]),
      ("Implement scan point GPS/coordinates mapping", ["Tap floor plan to scan", "Auto-position"]),
      ("Implement band comparison (2.4GHz vs 5GHz)", ["Split heatmaps", "Band recommendations"]),
      ("Implement channel overlap analysis", ["Channel utilization", "Interference detection"]),
      ("Create floor plan canvas with scan overlay", ["Image display", "Scan points", "Heatmap"]),
      ("Create scan walkthrough guide screen", ["Step-by-step instructions", "Progress"]),
      ("Create heatmap visualization screen", ["Color gradient overlay", "Legend", "Toggle layers"]),
      ("Create AP placement recommendation screen", ["Optimal positions", "Coverage gaps", "Suggestions"]),]),
    ("rork-pulselense", "PL", "PulseLense", "pulselense",
     ["Dashboard", "Metric", "Alert", "DataSource", "Widget"],
     [("Implement data source connector framework", ["Google Analytics", "Social APIs", "Custom webhook"]),
      ("Implement real-time metric updates", ["Supabase Realtime", "WebSocket", "Polling fallback"]),
      ("Implement alert engine with thresholds", ["Define thresholds", "Monitor metrics", "Push on trigger"]),
      ("Implement customizable dashboard builder", ["Widget library", "Drag-drop layout", "Resize"]),
      ("Implement chart rendering (line/bar/pie)", ["Chart.js or Victory", "Interactive", "Responsive"]),
      ("Implement anomaly detection algorithm", ["Statistical analysis", "Alert on anomaly", "Confidence"]),
      ("Implement scheduled report generation", ["Daily/weekly digest", "PDF format", "Email delivery"]),
      ("Implement metric comparison and correlation", ["Compare two metrics", "Correlation coefficient"]),
      ("Implement dashboard sharing with permissions", ["Share link", "View-only", "Collaborative"]),
      ("Implement data aggregation pipelines", ["Rollup hourly/daily", "Custom aggregations"]),
      ("Implement goal tracking per metric", ["Set targets", "Progress visualization", "Alerts"]),
      ("Implement historical data backfill", ["Import historical", "Fill gaps", "Reconcile"]),
      ("Create dashboard canvas with drag-drop widgets", ["Grid layout", "Resize handles", "Add widget"]),
      ("Create widget configuration modal", ["Data source", "Chart type", "Colors", "Refresh rate"]),
      ("Create alert management screen", ["Alert rules list", "Create/edit", "History"]),
      ("Create data source connection wizard", ["Select source", "Auth", "Select metrics", "Test"]),]),
    ("rork-simulive---multistream-studio", "SIM", "Simulive Multistream Studio", "simulive-studio",
     ["Stream", "Destination", "Schedule", "Recording", "Analytics"],
     [("Implement multi-destination RTMP management", ["Encrypted key storage", "Health monitoring", "Auto-reconnect"]),
      ("Implement stream scheduling system", ["Calendar integration", "Recurring", "Timezone"]),
      ("Implement pre-recorded simulive playback", ["Upload video", "Timed playback", "Chat integration"]),
      ("Implement stream analytics aggregation", ["Viewers per platform", "Peak concurrent", "Engagement"]),
      ("Implement stream health monitoring", ["Bitrate tracking", "Frame drops", "Audio levels"]),
      ("Implement go-live countdown and checklist", ["Pre-stream checklist", "Countdown timer"]),
      ("Implement chat aggregation from platforms", ["Multi-platform chat", "Unified view", "Moderate"]),
      ("Implement stream recording and archive", ["Auto-record", "Cloud storage", "Download"]),
      ("Implement thumbnail/overlay management", ["Upload overlays", "Position editor", "Scene switching"]),
      ("Implement stream key rotation for security", ["Rotate keys", "Update destinations", "History"]),
      ("Implement audience reach estimator", ["Historical data", "Platform metrics", "Prediction"]),
      ("Implement post-stream report generation", ["Metrics summary", "Platform comparison", "Highlights"]),
      ("Create stream scheduler calendar screen", ["Calendar view", "Create/edit events", "Recurring"]),
      ("Create multi-destination setup screen", ["Add platforms", "Enter keys", "Test connection"]),
      ("Create live stream dashboard", ["Health metrics", "Viewer counts", "Chat preview"]),
      ("Create stream analytics review screen", ["Charts per platform", "Comparison", "Export"]),]),
    ("rork-social-media-campaign-manager", "SC", "Social Media Campaign Manager", "social-campaigns",
     ["Campaign", "Post", "Analytics", "ContentTemplate", "Budget"],
     [("Implement multi-platform posting API", ["Meta, TikTok, X", "Media upload", "Caption adapt"]),
      ("Implement AI caption and hashtag generation", ["OpenAI/Claude", "Platform-optimized", "Trending"]),
      ("Implement campaign analytics aggregation", ["Cross-platform metrics", "ROI calculation"]),
      ("Implement content calendar with drag-drop", ["Visual calendar", "Drag to reschedule", "Bulk"]),
      ("Implement budget tracking and pacing", ["Spend tracking", "Budget pacing", "Overspend alerts"]),
      ("Implement A/B testing for posts", ["Create variants", "Split delivery", "Track winner"]),
      ("Implement UTM link builder and tracker", ["Auto-generate UTMs", "Click tracking", "Attribution"]),
      ("Implement approval workflow for posts", ["Submit for review", "Approve/reject", "Comments"]),
      ("Implement competitor campaign monitoring", ["Track competitors", "Content analysis", "Benchmarks"]),
      ("Implement media library for reusable assets", ["Upload/organize", "Tag", "Quick insert into posts"]),
      ("Implement post performance prediction AI", ["Historical analysis", "Predict engagement", "Timing recs"]),
      ("Implement influencer collaboration tracker", ["Partner list", "Deliverables", "Payment tracking"]),
      ("Create campaign builder wizard", ["Objective", "Platforms", "Budget", "Schedule"]),
      ("Create content calendar screen", ["Calendar grid", "Post previews", "Status colors"]),
      ("Create post composer screen", ["Multi-platform preview", "Media attach", "Schedule"]),
      ("Create campaign analytics dashboard", ["Cross-platform charts", "ROI", "Top posts"]),]),
    ("rork-sora-watermark-remover", "SWR", "Sora Watermark Remover", "sora-watermark",
     ["Video", "ProcessingJob", "Template", "BatchJob"],
     [("Implement video upload with chunked upload", ["Progress bar", "Size validation", "Resume support"]),
      ("Implement watermark detection algorithm", ["Frame analysis", "Region detection", "Confidence"]),
      ("Implement video processing pipeline", ["FFmpeg or cloud", "Inpainting", "Quality preserve"]),
      ("Implement processing queue with status", ["Background queue", "Realtime status", "Retry"]),
      ("Implement processed video download", ["Download link", "Share", "Auto-cleanup 30 days"]),
      ("Implement batch video processing", ["Upload multiple", "Queue all", "Progress per video"]),
      ("Implement before/after preview", ["Side-by-side", "Slider comparison", "Frame scrub"]),
      ("Implement custom watermark region selection", ["Draw region on frame", "Adjust bounds"]),
      ("Implement video trim before processing", ["Start/end selection", "Preview trim"]),
      ("Implement quality/resolution selection", ["Output resolution", "Compression level", "Format"]),
      ("Implement processing history and re-download", ["History list", "Re-download", "Delete"]),
      ("Implement watermark template detection", ["Known watermark patterns", "Auto-detect Sora"]),
      ("Create video upload screen with progress", ["Drag-drop or picker", "Progress bar", "Preview"]),
      ("Create processing status screen", ["Queue position", "Progress", "ETA"]),
      ("Create before/after comparison screen", ["Slider overlay", "Side-by-side", "Frame select"]),
      ("Create batch processing dashboard", ["All jobs", "Status per video", "Overall progress"]),
      ("Implement video format detection and compatibility check", ["Detect codec/format", "Warn unsupported", "Suggest conversion"]),
      ("Implement processing cost estimation per tier", ["Estimate based on duration/resolution", "Show before process", "Tier limits"]),
      ("Implement video thumbnail extraction for preview", ["Extract key frames", "Grid preview", "Scrub timeline"]),
      ("Implement watermark region template saving", ["Save detected region", "Apply to similar videos", "Template library"]),
      ("Implement video metadata preservation", ["Keep audio track", "Preserve duration", "Maintain aspect ratio"]),
      ("Implement processing notification on completion", ["Push when done", "Email option", "In-app toast"]),
      ("Implement video frame-by-frame inspector", ["Step through frames", "Zoom on region", "Compare original"]),
      ("Implement cloud processing via Supabase Edge Function", ["Upload to Storage", "Trigger processing", "Return result URL"]),
      ("Create watermark region selector overlay", ["Draw rectangle on frame", "Resize handles", "Preview inpaint"]),
      ("Create processing tier comparison screen", ["Free vs Pro limits", "Speed comparison", "Quality options"]),
      ("Create video inspector frame-by-frame screen", ["Frame navigation", "Zoom controls", "Region highlight"]),]),
    ("rork-strongface", "SF", "StrongFace", "strongface",
     ["Exercise", "Routine", "Progress", "Achievement", "ScheduledSession"],
     [("Implement guided routine player with timer", ["Step-by-step", "Rest periods", "Audio cues"]),
      ("Implement progress tracking with photos", ["Before/after Supabase Storage", "Timeline", "Comparison"]),
      ("Implement custom routine builder", ["Select exercises", "Set reps/duration", "Save/share"]),
      ("Implement streak and achievement system", ["Daily streak", "Badges", "Push reminders"]),
      ("Implement AI form analysis via camera", ["Face detection", "Form correction", "Rep counting"]),
      ("Implement exercise difficulty progression", ["Track improvement", "Suggest harder variations"]),
      ("Implement rest day scheduling", ["Recovery recommendations", "Calendar integration"]),
      ("Implement workout reminder notifications", ["Configurable schedule", "Motivational messages"]),
      ("Implement social sharing of progress", ["Progress photo card", "Stats summary", "App link"]),
      ("Implement muscle group targeting", ["Face muscle map", "Target specific areas", "Balanced routine"]),
      ("Implement video instruction playback", ["Exercise demo videos", "Mirror mode", "Speed control"]),
      ("Implement session rating and notes", ["Rate difficulty", "Notes per session", "Track fatigue"]),
      ("Create routine player screen with timer", ["Large timer", "Exercise visual", "Next up preview"]),
      ("Create progress photo timeline screen", ["Side-by-side photos", "Date markers", "Zoom"]),
      ("Create routine builder screen", ["Exercise library", "Drag to reorder", "Preview"]),
      ("Create achievement gallery screen", ["Badges grid", "Locked/unlocked", "Progress"]),]),
    ("rork-unified-media-gallery-app", "UMG", "Unified Media Gallery", "unified-media",
     ["MediaItem", "Source", "Album", "SyncJob", "SharedAlbum"],
     [("Implement Google Photos API integration", ["OAuth", "Album sync", "Incremental updates"]),
      ("Implement Instagram media sync", ["Graph API", "Media download", "Caption preserve"]),
      ("Implement unified search across sources", ["Full-text search", "Filter by source/date", "AI tags"]),
      ("Implement smart album creation with AI", ["Auto-categorize", "Face grouping", "Location"]),
      ("Implement media backup to Supabase Storage", ["Selective backup", "Quota per tier", "Restore"]),
      ("Implement source connection OAuth flow", ["Per-platform OAuth", "Token refresh", "Revoke"]),
      ("Implement sync scheduling and incremental", ["Background sync", "Delta only", "Conflict handling"]),
      ("Implement face detection and people albums", ["Detect faces", "Cluster", "Name people"]),
      ("Implement location-based album suggestions", ["GPS from EXIF", "Group by location", "Map view"]),
      ("Implement media deduplication", ["Hash comparison", "Cross-source dedup", "Merge"]),
      ("Implement album sharing with link", ["Generate link", "View-only access", "Password protect"]),
      ("Implement slideshow/presentation mode", ["Auto-play", "Transitions", "Background music"]),
      ("Create media grid gallery screen", ["Thumbnails", "Pinch zoom", "Select mode"]),
      ("Create source management screen", ["Connected sources", "Sync status", "Add/remove"]),
      ("Create album detail screen", ["Media grid", "Album info", "Share/export"]),
      ("Create people/faces gallery screen", ["Face clusters", "Name labels", "Browse by person"]),]),
    ("rork-vlogflow--plan---film", "VF", "VlogFlow Plan and Film", "vlogflow",
     ["Vlog", "Shot", "Script", "Location", "Equipment"],
     [("Implement AI script generation from topic", ["OpenAI/Claude", "Outline first", "Full script"]),
      ("Implement shot list management", ["Reorder shots", "Assign clips", "Status tracking"]),
      ("Implement filming checklist with GPS", ["Location tracking", "Equipment list", "Weather"]),
      ("Implement vlog publishing analytics", ["Views, engagement", "Cross-platform", "Content insights"]),
      ("Implement filming location scouting tools", ["Map view", "Save locations", "Photos/notes"]),
      ("Implement equipment checklist templates", ["Camera, audio, lighting", "Custom items", "Check off"]),
      ("Implement video clip annotation", ["Tag clips to shots", "Rate takes", "Select best"]),
      ("Implement AI thumbnail suggestions", ["Generate thumbnails", "A/B test options", "Click-through prediction"]),
      ("Implement collaboration for crew members", ["Invite crew", "Assign roles", "Shared shot list"]),
      ("Implement weather integration for outdoor shoots", ["Weather forecast", "Alert on bad weather"]),
      ("Implement script teleprompter mode", ["Auto-scroll", "Speed control", "Highlight current"]),
      ("Implement post-production checklist", ["Edit steps", "Review stages", "Publish checklist"]),
      ("Create shot list screen with drag-reorder", ["Shot cards", "Status icons", "Drag handle"]),
      ("Create script editor screen", ["Text editor", "Timestamp markers", "Teleprompter mode"]),
      ("Create filming location map screen", ["Map pins", "Location details", "Navigate"]),
      ("Create vlog project timeline screen", ["Planning > Filming > Editing > Published", "Progress"]),]),
    ("rork-voice-to-letter-love-notes", "VL", "Voice-to-Letter Love Notes", "voice-love-notes",
     ["VoiceNote", "Letter", "Template", "Recipient", "Delivery"],
     [("Implement voice-to-text with Whisper API", ["Audio recording", "Transcription", "Multi-language"]),
      ("Implement AI letter formatting with style", ["OpenAI/Claude", "Multiple styles", "Grammar correct"]),
      ("Implement letter template system", ["Beautiful templates", "Custom fonts/colors", "Themes"]),
      ("Implement letter delivery options", ["Email", "PDF download", "Share link with animation"]),
      ("Implement handwriting font rendering", ["Script fonts", "Stationery backgrounds", "Wax seal"]),
      ("Implement voice recording with waveform", ["Record button", "Waveform visual", "Duration"]),
      ("Implement letter preview with animations", ["Unfolding animation", "Reveal effect", "Music"]),
      ("Implement recipient management", ["Save recipients", "Delivery history", "Favorites"]),
      ("Implement occasion-based templates", ["Valentine, Birthday, Anniversary", "Seasonal themes"]),
      ("Implement audio attachment to letter", ["Include voice recording", "Playback in letter view"]),
      ("Implement letter collection/album", ["Group letters", "Timeline view", "Memory book"]),
      ("Implement letter scheduling for future delivery", ["Schedule delivery", "Reminder before", "Auto-send"]),
      ("Create voice recording screen with waveform", ["Large record button", "Waveform", "Timer"]),
      ("Create letter preview screen", ["Template applied", "Handwriting font", "Actions"]),
      ("Create template gallery screen", ["Browse themes", "Preview", "Select"]),
      ("Create delivery options screen", ["Email/PDF/link", "Recipient select", "Schedule"]),]),
]

for slug, prefix, name, prompt_slug, entities, extras in SIMPLE_APPS:
    APPS[slug] = (prefix, name, prompt_slug, entities, {"domain": extras})

print(f"App definitions loaded: {len(APPS)}")
